/'
author: Tim
'/
@startuml

!include style.puml

Component Model {
    Component "Database \nCommunication" as DBC
    Component "Calculation" as C
    Component "Data Formatting" as DF

    () "modified data" as MF
    () "author and \npaper data" as APD

    port " " as fd
    'interface to add new indices
    portin "index plugin" as iplug
    portin " " as iapi
    portin " " as sapi
    portin " " as uapi
}

Database IEEEXplore as IEEE
Database "User profiles" as UP
Database "Semantic Scholar" as SS

() "IEEEXplore API" as IAPI
() "Semantic Scholar API" as SAPI
() "User profile API" as UAPI
() "Formatted Data" as FD

'provided Interfaces
fd -up- FD
IEEE -up- IAPI
UP -up- UAPI
SS -up- SAPI
DBC -left- APD
C -up- MF

'ports
DF <- fd : <<delegate>>
DBC -> iapi : <<delegate>>
DBC -> sapi : <<delegate>>
DBC -> uapi : <<delegate>>

'required Interfaces
iapi -down-( IAPI : get papers \n and authors
sapi -down-( SAPI : get papers \n and authors
uapi -down-( UAPI : get/send \nuser data
C -right-( APD : use
C .up.> iplug : plugin index calc
DF .up.> iplug : plugin index format
DF -left-( MF : use
DF --( APD : use


'formatting
DBC -[hidden]down- DF
DBC -[hidden]down- C
DBC -[hidden]left- APD
C -[hidden]down- MF
DF -[hidden]right- MF
C -[hidden]right- APD

@enduml